name: Publish Docker image
on:
  push:
    branches:
      - debug
jobs:
  Build_Multi_Architecture:
    runs-on: Sirius01
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: debug

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
            
      - name: Build
        run: |
          docker buildx --use lycoris build --platform linux/amd64,linux/arm64 -t ${{secrets.DOCKER_USERNAME}}/docker-texlive-ja:debug .
