name: Publish Docker image
on:
  push:
    branches:
      - test/github
jobs:
  Build:
    runs-on: Sirius01
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
            
      - name: Make Cache
        uses: docker/build-push-action@v3
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{secrets.DOCKER_USERNAME}}/docker-texlive-ja:cache
          cache-from: type=registry,ref=${{secrets.DOCKER_USERNAME}}/docker-texlive-ja:cache
          cache-to: type=registry,ref=${{secrets.DOCKER_USERNAME}}/docker-texlive-ja:cache,mode=max

      - name: Make Cache
        uses: docker/build-push-action@v3
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{secrets.DOCKER_USERNAME}}/docker-texlive-ja:${{ github.ref_name }}
          cache-from: type=registry,ref=${{secrets.DOCKER_USERNAME}}/docker-texlive-ja:cache


