name: Publish Docker image
on:
  push:
    branches:
      - master
      - build-cache
      - debug
jobs:

  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
            
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: unicatflower/docker-texlive-ja:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

