name: Publish Docker image
on:
  push:
    branches:
      - debug
jobs:
  Build_Multi_Architecture:
    name: buid and publish for linux/amd64 & linux/arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
            
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: unicatflower/docker-texlive-ja:test
          cache-from: type=registry,ref=unicatflower/docker-texlive-ja:buildcache
          cache-to: type=registry,ref=unicatflower/docker-texlive-ja:buildcache,mode=max
