name: Publish Docker image
on:
  push:
    branches:
      - test/github
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: unicatflower/docker-texlive-ja:cache
          cache-from: type=registry,unicatflower/docker-texlive-ja:cache
          cache-to: type=registry,unicatflower/docker-texlive-ja:cache,mode=max
