name: Publish Docker image
on:
  push:
    branches:
      - debug
jobs:
  Build_Multi_Architecture:
    name: buid and publish for linux/amd64 & linux/arm64
    runs-on: Sirius01
    steps:
      - uses: actions/checkout@v3
        with:
          ref: debug
            
      - name: Build
        uses: Sirius01
        run: |
          docker buid --platform linux/amd64,linux/arm64 -t ${{secrets.DOCKER_USERNAME}}/docker-texlive-ja:debug .
