name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:
  Build_Multi_Architecture:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
            
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: amd64/linux,arm64/linux
          tags: unicatflower/docker-texlive-ja:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  Build_x86_64:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
            
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: amd64/linux
          tags: unicatflower/docker-texlive-ja:x86_64.latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  Build_arm64:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
            
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: arm64/linux
          tags: unicatflower/docker-texlive-ja:arm64.latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

