name: Publish Docker image
on:
  push:
    branches:
      - debug
jobs:
  Build_Multi_Architecture:
    runs-on: Sirius01
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: debug

      - name: Build
        run: |
          docker buid --platform linux/amd64,linux/arm64 -t ${{secrets.DOCKER_USERNAME}}/docker-texlive-ja:debug .
